### ISSUE TITLE
关于c++20编译的问题

### ISSUE THREAD

**Issue by dracodearys** [zavier-wong/acid#1]
我是ubuntu系统，更新了g++-11。
在cmake中设置 '-std=c++20' ，make时会报错
`c++: error: unrecognized command line option ‘-std=c++20’; did you mean ‘-std=c++2a’?`
如果改为 '-std=c++2a' 又会报
`fatal error: concepts: No such file or directory`

希望更详细地说明一下项目中c++20如何通过编译，谢谢！

**Comment by zavier-wong** [comment]
你好，可能是g++版本不够新，请问是按照README上的方法更新吗
```
sudo apt install software-properties-common
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt install gcc-11 g++-11
```

**Comment by dracodearys** [comment]
> 你好，可能是g++版本不够新，请问是按照README上的方法更新吗
> 
> ```
> sudo apt install software-properties-common
> sudo add-apt-repository ppa:ubuntu-toolchain-r/test
> sudo apt install gcc-11 g++-11
> ```

是的☹

**Comment by zavier-wong** [comment]
直接g++ -v是什么版本，可能还要链接到g++-11，我找找cmake怎么指定编译工具，你链接一下可以先解决这个问题

**Comment by zavier-wong** [comment]
cmake里加入这行就行 `set (CMAKE_CXX_COMPILER "/usr/bin/g++-11") `
我等下会更新cmake，还有修复大量bug

**Comment by dracodearys** [comment]
> 

确实是，亲测有效，谢谢！我还比较小白😁

**Comment by brinkqiang** [comment]
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 200
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 200


> > 
> 
> 确实是，亲测有效，谢谢！我还比较小白😁
