### ISSUE TITLE
rpc 是否支持http2.0

### ISSUE THREAD

**Issue by wjbbupt** [zavier-wong/acid#10]
你好，首先我觉得写的挺好的，我有个问题，这个http支持http2.0嘛 ，因为rpc是一对一的，我之前用过rpc是支持http2.0 的，然后它社区也有对应协成的一些仓库，如果这边可以改善是个很好的点 我也试着学习修改

**Comment by zavier-wong** [comment]
感谢您的建议，但项目本身的重点并不在web上，后续应该还是朝着分布式共识，分布式kv存储，注册中心集群这些方向发展

**Comment by wjbbupt** [comment]
我也在搞分布式，不过我使用的框架是 grpc  dds这些  他们有个优点就是代码生成器  分布式存储  注册发现等之前有redis  不过现在好像出来一个比redis  性能更好的，不过很多人真在使用 ，这也是个很好的点

**Comment by zavier-wong** [comment]
hh，主要还是自己写着玩的，现有的框架自然是经过了时间的考验
