### ISSUE TITLE
大佬您好，我想请教一下我在tests/kvraft编译的时候遇到缺少raft库的情况

### ISSUE THREAD

**Issue by JimmyRowe13** [zavier-wong/acid#14]
![image](https://github.com/zavier-wong/acid/assets/73340805/576e4485-1403-46c5-a154-3ffa21cfcbaa)
请问这个库是什么情况呢，本人是刚入门的小白，望大佬不吝赐教^^

**Comment by zavier-wong** [comment]
你没有先把库编译出来
```
3.构建项目 / Build

mkdir build
cd build
cmake ..
make
```
在acid/lib目录下要编译出libacid.a  libraft.a

**Comment by JimmyRowe13** [comment]
我make后好像只有一个libacid.a，并没有看到libraft.a，T_T，是只需要在acid/build这个目录下编译还是还有其他文件夹需要@@
![image](https://github.com/zavier-wong/acid/assets/73340805/09c013b9-0a40-407f-a76f-602eff04dc06)

**Comment by zavier-wong** [comment]
我知道了，之前改过一次cmake，你把tests/kvraft和tests/raft下的cmake里set(LINK_ARGS... raft...)这个raft去掉就行

**Comment by zavier-wong** [comment]
已经更新了，你可以重新git pull一下

**Comment by JimmyRowe13** [comment]
可以了，感谢大佬
