### ISSUE TITLE
请问如果想在example中新增其他的provider和consumer改如何处理呢

### ISSUE THREAD

**Issue by JimmyRowe13** [zavier-wong/acid#16]
对于makefile这块不是很熟悉，感觉看着好乱，望大佬提供点思路^^

**Comment by zavier-wong** [comment]
你可以改改provider的程序，根据命令行参数来帮绑定端口，这样多开几个程序就行了

**Comment by zavier-wong** [comment]
https://github.com/zavier-wong/acid/blob/main/example/kvhttp/kvhttp_server.cpp
参考一下这个example

**Comment by JimmyRowe13** [comment]
好的
