### ISSUE TITLE
关于LogManager中m_loggers类型的问题

### ISSUE THREAD

**Issue by Ryu-5973** [zavier-wong/acid#4]
这里m_loggers类型是map<std::string,Logger::ptr>，但我看具体实现好像对key的排序没啥要求，如果只是单纯哈希的话，是不是unordered_map会更好一点，毕竟map底层是红黑树，一次查询的复杂度是O(logN)级别的，而unordered_map是O(1)

**Comment by zavier-wong** [comment]
都可以，unordered_map时间复杂度虽然是O(1)的，但是常数比较大。logger一般也不会很多，所以这两者效率不会差太多
