### ISSUE TITLE
关于协程的实现

### ISSUE THREAD

**Issue by JLU-Neal** [zavier-wong/acid#8]
嗨！ 你好，看了这个repo感觉受益匪浅！
有问题想请教一下， 按照我的理解，这个repo里的协程似乎并没有使用C++ 20 里的标准， 而是通过定义Fiber类自己实现了一套协程？

**Comment by zavier-wong** [comment]
无栈协程的性能好，但是传染性高而且目前缺少了一大堆协程组件比较难用，有栈协程比较友好一点。但在需要性能的地方比如协程状态机解析HTTP这部分我还是使用了无栈协程来获取更高的解析效率。算是个折中的方案。

**Comment by JLU-Neal** [comment]
好的，十分感谢！
